org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.targetSdk=34
android.compileSdk=35
android.minSdk=24
BUNDLE_ID=com.alvaropassalacqua.squishflow
app.versionCode=1
app.versionName=1.0.0
kotlin.version=2.3.20
agp.version=8.9.2
compose.version=1.11.0
